---
After: 'toolbar/*'
---
SSViewer:
  theme: addons
GlobalNav:
  hostname: '//www.silverstripe.org/'
  css_path: '/themes/ssv3/css/toolbar.css'
  use_localhost: false
GlobalNavTemplateProvider:
  connection_timeout: 2000
  transfer_timeout: 6000